import { FormEvent, useState } from 'react';
import { AdHocImpactLevel, AD_HOC_IMPACT_LEVELS, AdHocObservation } from '../../types/methodology';

interface AdHocAssessmentProps { observations: AdHocObservation[]; onChange: (observations: AdHocObservation[]) => void; }
type ObservationDraft = Omit<AdHocObservation, 'id'>;
const emptyDraft: ObservationDraft = { component: 'Physical', observation: '', impact: 'Moderate', mitigation: '' };

export default function AdHocAssessment({ observations, onChange }: AdHocAssessmentProps) {
    const [draft, setDraft] = useState<ObservationDraft>(emptyDraft);
    const [editingId, setEditingId] = useState<string | null>(null);
    const updateDraft = (key: keyof ObservationDraft, value: string) => setDraft({ ...draft, [key]: value } as ObservationDraft);
    const submit = (event: FormEvent) => { event.preventDefault(); if (!draft.observation.trim()) return; if (editingId) onChange(observations.map((item) => item.id === editingId ? { ...draft, id: editingId } : item)); else onChange([...observations, { ...draft, id: `observation-${Date.now()}` }]); setDraft(emptyDraft); setEditingId(null); };
    const edit = (observation: AdHocObservation) => { setEditingId(observation.id); setDraft({ component: observation.component, observation: observation.observation, impact: observation.impact, mitigation: observation.mitigation }); };
    return <section><div className="methodology-heading"><div><p className="eyebrow">Qualitative field observation</p><h2>Ad-Hoc Assessment</h2><p>Capture observations and proposed mitigation measures that require professional judgement.</p></div><span className="methodology-count">{observations.length} observation{observations.length === 1 ? '' : 's'}</span></div><form className="adhoc-form" onSubmit={submit}><div className="adhoc-form__grid"><label>Environmental Component<select value={draft.component} onChange={(event) => updateDraft('component', event.target.value)}><option>Physical</option><option>Biological</option><option>Natural Resources</option><option>Socio-Economic</option></select></label><label>Potential Impact Level<select value={draft.impact} onChange={(event) => updateDraft('impact', event.target.value)}>{AD_HOC_IMPACT_LEVELS.map((level) => <option key={level}>{level}</option>)}</select></label></div><label>Observation / Description<textarea value={draft.observation} onChange={(event) => updateDraft('observation', event.target.value)} placeholder="Describe the observed environmental interaction or concern." rows={3} /></label><label>Potential Mitigation Measure<textarea value={draft.mitigation} onChange={(event) => updateDraft('mitigation', event.target.value)} placeholder="Describe a feasible mitigation or management measure." rows={3} /></label><button type="submit" className="secondary-button">{editingId ? 'Save Observation' : 'Add Observation'}</button>{editingId && <button type="button" className="text-button" onClick={() => { setEditingId(null); setDraft(emptyDraft); }}>Cancel edit</button>}</form>{observations.length > 0 && <div className="observation-list">{observations.map((observation) => <article className="observation-row" key={observation.id}><div className="observation-row__head"><span>{observation.component}</span><b>{observation.impact}</b></div><strong>{observation.observation}</strong><p>{observation.mitigation || 'No mitigation measure recorded.'}</p><div><button type="button" className="text-button" onClick={() => edit(observation)}>Edit</button><button type="button" className="text-button text-button--danger" onClick={() => onChange(observations.filter((item) => item.id !== observation.id))}>Remove</button></div></article>)}</div>}</section>;
}
