import { AssessmentData, ASSESSMENT_CATEGORIES } from '../../types/assessment';
import { AssessmentSite } from '../../types/location';
import { countInventoryEntries, countMatrixEntries, SiteMethodology } from '../../types/methodology';

interface MethodologyReviewProps { site: AssessmentSite; assessment: AssessmentData[string]; methodology: SiteMethodology; onViewResults: () => void; }

export default function MethodologyReview({ site, assessment, methodology, onViewResults }: MethodologyReviewProps) {
    return <section><div className="methodology-heading"><div><p className="eyebrow">EIA data review</p><h2>Methodology Review</h2><p>Structured inventory and user-assisted methodology inputs for the active site.</p></div><div className="methodology-site-meta"><strong>{site.label} · {site.name.split(',')[0]}</strong><span>{site.latitude.toFixed(5)}, {site.longitude.toFixed(5)}</span></div></div><div className="methodology-review-grid"><div className="methodology-review-block"><h3>Checklist Summary</h3><strong>{countInventoryEntries(assessment)} / {ASSESSMENT_CATEGORIES.reduce((sum, category) => sum + category.parameters.length, 0)} inventory entries</strong><p>{ASSESSMENT_CATEGORIES.map((category) => `${category.shortLabel}: ${Object.values(assessment[category.id]).filter(Boolean).length}/${category.parameters.length}`).join(' · ')}</p></div><div className="methodology-review-block"><h3>Matrix Summary</h3><strong>{countMatrixEntries(methodology.matrix)} / 20 impact entries</strong><p>Impact levels recorded by project activity and environmental component.</p></div><div className="methodology-review-block"><h3>Ad-Hoc Observations</h3><strong>{methodology.observations.length} observation{methodology.observations.length === 1 ? '' : 's'}</strong><p>Qualitative observations and mitigation measures recorded for this site.</p></div></div><button type="button" className="primary-button methodology-results-button" onClick={onViewResults}>View Comparative Analysis</button></section>;
}
